# Generated by Django 3.2.16 on 2022-11-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='test-slug-for-first-recipe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
