# Generated by Django 3.2.16 on 2022-11-22 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20221122_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='slug',
            new_name='slugtest',
        ),
    ]
