# Generated by Django 3.2.16 on 2022-11-22 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_rename_slug_recipe_slugtest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='slugtest',
            new_name='slug',
        ),
    ]
