# Generated by Django 3.2.16 on 2022-11-25 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_rename_category_recipe_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
