# Generated by Django 3.2.16 on 2022-11-23 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_rename_slugtest_recipe_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='brief_description',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='instruction',
            new_name='full_description',
        ),
    ]
